---
- name: Install ufw
  action: apt update_cache=yes name=ufw
  tags:
    - ufw
    - install 

- name: Enable ufw logging
  ufw: logging=on
  tags:
    - ufw
    - config

- name: Enable ufw and deny by default
  ufw: state=reset policy=deny
  tags:
    - ufw
    - config

- name: Open incoming on specified ports
  ufw: 
    rule: allow 
    proto: tcp 
    port: "{{ item }}"
  with_items: "{{ ufw_open_ports }}"
  tags:
    - ufw
    - config  

- name: Restart ufw
  ufw: state=enabled
  tags:
    - ufw
    - config  
